version: '3.7'

services:
  db:
    image: postgres:12-alpine
    container_name: db
    env_file:
      - '.env'
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
    command: mix phx.server
    env_file:
      - '.env'
    depends_on:
      - db
    ports:
      - 4000:4000
    volumes:
      - .:/app

volumes:
  postgres_data:
